from vector2 import Vector2

# General settings
SCREEN_WIDTH = 512 * 2
SCREEN_HEIGHT = 320 * 2
BACKGROUND_COLOR = (161, 161, 161)

# Ally faction
ALLY_INFANTRY_COLOR = (47, 140, 255) # 7 < unit.health <= 10
ALLY_WOUNDED_INFANTRY_COLOR = (110, 175, 255) # 3 < health <= 7
ALLY_HEAVILY_WOUNDED_INFANTRY_COLOR = (154, 200, 255) # 0 < health <= 3
ALLY_SPAWN_POINT = Vector2(0,0) # Top left corner of screen
ALLY_RETREAT_POSITION = ALLY_SPAWN_POINT
ALLY_ADVANCEMENT_POINT = Vector2(SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
ALLY_NUMBER_OF_UNITS = 20


# Enemy faction
ENEMY_INFANTRY_COLOR = (255, 125, 19) # 7 < unit.health <= 10
ENEMY_WOUNDED_INFANTRY_COLOR = (255, 157, 77) # 3 < health <= 7
ENEMY_HEAVILY_WOUNDED_INFANTRY_COLOR = (255, 200, 154) # 0 < health <= 3
ENEMY_SPAWN_POINT = Vector2(SCREEN_WIDTH,SCREEN_HEIGHT) # Bottom right corner of screen
ENEMY_RETREAT_POSITION = ENEMY_SPAWN_POINT
ENEMY_ADVANCEMENT_POINT = Vector2(SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
ENEMY_NUMBER_OF_UNITS = 20


# Infantry unit stats
INFANTRY_SPEED = 50
INFANTRY_RANGE = 200
INFANTRY_RADIUS = 5
INFANTRY_MAX_HEALTH = 10
INFANTRY_RELOAD_DURATION = 200
INFANTRY_WOUNDED_THRESHOLD = 0.7 * INFANTRY_MAX_HEALTH # 70% of max health
INFANTRY_HEAVILY_WOUNDED_THRESHOLD = 0.3 * INFANTRY_MAX_HEALTH # 30% of max health

# Projectile stats
PROJECTILE_COLOR = (0,0,0)
PROJECTILE_SPEED = 300
PROJECTILE_DAMAGE = 4
PROJECTILE_RADIUS = 1